version: '3.8'

services:

  #PHP Service
  app:
    container_name: "chatbots_app"
    build:
      context: "./fpm/"
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - "../:/var/www/html"
    depends_on:
      - db

  #Nginx Service
  webserver:
    container_name: "chatbots_webserver"
    image: "nginx"
    ports:
      # - "${APP_PORT}:80"
      - "80:80"
      - "6001:6001"
    volumes:
      - "../:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"

  # DB UI management service
  adminer:
    container_name: "chatbots_adminer"
    image: "phpmyadmin:latest"
    ports:
      # - ${ADMINER_PORT}:8080
      - "85:80"
    depends_on:
      - db

  #MySQL Service
  db:
    container_name: "chatbots_db"
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: chatbots
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./data/db:/var/lib/mysql/"
